### PR TITLE
Keep the most recently used log filters in the user history

### PR DESCRIPTION
**Pull request by Arkanosis**
This PR replaces the log filter text field with a combo box and an MRU list of log filters, similar to the MRU list of paths / URIs used when adding a new data source.

### CODE REVIEW

**Comment by fthevenet** [comment]
Hi @Arkanosis and thanks for taking on this long overdue feature - I always meant to implement it, but got distracted along the way, and never took the time to properly do it.

I've tried your implementation and it is promising, although not without issues.
The main one is that of the persistence of the Most Recently Used list across different worksheets; at the moment, a new MRU list is instantiated per worksheet but they all share the same back-end for persistence, i.e. per user on the local machine.
This causes cached search terms from one worksheet to "leak" into other worksheets but inconsistently, depending on the order in which worksheets were created.
This also causes inconsistent storage of the terms into the persistent store, as the multiple lists that share it are not synchronized.

Before fixing it we need to specify  the desired behaviour. Off the top of my head, we could have:
1. All worksheets share a single MRU list, persisted across sessions via the user settings: to do that, simply make the list a member of UserHistory and reuse this single list for all worksheets. Search terms will still be shared across worksheet, but in a consistent way.
2. Each worksheet have its own private MRU, so that terms are not shared. In this case, we could  persist their content as part of UserHistory by generating a unique key for each. I'm not sure it's a great idea though, as user profile will end up being cluttered with history from never used again workspace. Then we might want to:

      - Not persist suggestions across sessions at all i.e. just use an MRU without a back-end; all suggestions will be per worksheet, but will be lost when the  workspace it closed. I don't remember if I've implemented a volatile MRU list yet or not.
      - Persists suggestions as part of the worksheet itself, so that they are serialized as part of the workspace. This means that suggestions will be shared with other potentials users of that workspace, though. I can't really think of a case where this might be a real issue (and in fact could be useful most of the time), but or course that's something to be aware of. 
    
    These are my initial thoughts on how to implement this feature; I'm looking forward to reading yours.

**Comment by fthevenet** [comment]
Also, while we're at it, it would probably make sense to have as-you-type suggest list as well as a drop down list, since it is the behaviour that most users would expect from a search bar, I guess.

**Comment by fthevenet** [comment]
PS: As I've checked out your branch to review and test it, it is a more straight forward for me to keep track of it if you don't force push.
I'll do a squash and merge at the end anyway, to have a single, nice, clean commit.

**Comment by Arkanosis** [comment]
Hi @fthevenet, thanks for the review!

The benefit of the feature for me is the ability to reuse filters from one workspace to another as much as within a single workspace. Therefore, of the behaviors you list, my preference goes to the first one: a single MRU list shared across all worksheets and persisted across sessions via the user history.

That being said, I also get the appeal of storing / sharing filters together with workspaces — not to add isolation between worksheets, but between workspaces, as well as to allow sharing with other users of the same workspaces. I'd rather see this as an explicit bookmarking than as an MRU list, though. Actually, my initial intention was to implement some kind of filter bookmarks in the user preferences, but I went for the MRU list as an equally useful and easier to implement feature.

The best behavior I can think of would be to have three lists instead of one:
 - the list of MRU filters, which is implicitly stored in the user history and never shared (requires no effort to use, but can contain garbage and lose filters after some time);
 - the list of user favorite filters, which is explicitly stored in the user preferences and never shared (requires some effort to use, but guarantees both the cleanliness and the durability of the filters);
 - the list of workspace filters, which is explicitly stored in the workspace and shared with it (same effort and same benefits + isolation with other workspaces and sharing with other users).
The three lists would be displayed in the same combo box (can we have sections with this widget in JavaFX?), kind of like how awesome bars of web browsers display the history, the bookmarks and the search suggestions at the same time.

I think these lists could be added in this order, though. The MRU is the easiest to implement; the user and workspace favorites requires some additional work.

Also, +1 for the autocomplete; this goes hand in hand with awesome bars :)

**Comment by fthevenet** [comment]
OK, sounds good to me!

As hinted earlier, this should also be the easiest to implement/least amount of extra work: simply declare and initialize your suggestion list in `UserHistory` (see `logFilesHistory` or `mostRecentWorkspaces`) and call it on the singleton from the controller.
I don't believe there's any reason to be concerned with concurrency issues here, so this should be straight forward.

I like the idea of having a way to separately and explicitly bookmark terms, though I'm not entirely sure about distinguishing user local bookmarks from workspace bookmarks, as I fear it might be difficult to quickly grasp the distinction in between the two and just end up being confusing.

At any rate I suggest you create a follow up issue to track and discuss this enhancement further and that we keep this PR focused on your original idea since it is now well defined.

With regard to the auto-completion, I suggest you have a look at the implementation in [`DataAdapterDialog`](https://github.com/binjr/binjr/blob/7fed8871ee8fe3b3bf8b16dfa4f4094b99b73400/binjr-core/src/main/java/eu/binjr/core/dialogs/DataAdapterDialog.java#L54), if you haven't already (`AutoCompletionBinding<String> autoCompletionBinding` is what you are looking for)

**Comment by Arkanosis** [comment]
There is now a single ObservableList shared between comboboxes on all worksheets and all autocompletion bindings.

I still see two issues with the current implementation:
 - for some reason, selecting an entry from the combobox opens the autocompletion popup; I haven't been able to understand why (if you know about some way to log UI events…);
 - I'd love to add new MRU entries to the top of the combobox entries, but it seems that JavaFX keeps track of the currently selected entry by position, which as far I as can tell makes it impossible — I therefore add new entries to the bottom, but I'm less pleased by the behavior.

**Comment by fthevenet** [comment]
It appears the troubles with the ordering of the suggestions stem from the fact that you're battling with 2 separate lists; the MRU itself (which already behave exactly like you want) and the `ObservableList` that is used as a backend for the `ComboBox` control.
This can be fixed easily by making the the combobox as dumb as possible and overwriting its own list with the content of the MRU right before displaying it.
You can see an example of that in this commit https://github.com/binjr/binjr/commit/8444f5c51bbf550fe668d657ddd6f2d178baa5c8.

With that said, this now means that the `ComboBox` control is probably too "smart" a control for what we're doing, and a dumb drop down list (e.g. non "observable" or anything) would serve us well here. This added to the fact that I don't like the position of the "down arrow"  button relative to the other buttons in the bar, means that we should probably replace that with a simple button (that we can place wherever we choose) and a `ContextMenu` directly populated with the content of the MRU on showing.

**Comment by fthevenet** [comment]
On the topic of the autocomplete, it turns out the control I pointed out is pretty finicky  - and getting it to work exactly as we want is a pain because it comes with its own display popup.
So I'm of a mind that we'd be better off replacing it altogether with a custom implementation, especially if we want to support bookmarks later down the line: we certainly don't want to managed a *third* dropdown list for that...

Therefore I now think we forget it for the time being and we address it alongside the "bookmark" feature we discussed previously.

**Comment by Arkanosis** [comment]
I wondered about implementing the `ObservableList` interface directly in the MRU, but your approach is simpler and I'm not sure being observable would be any better anyway (or work at all).

So I have merged your last commit and removed autocomplete for now, and I'm quite happy with the current behavior.

I let you decide if the PR is worth merging and I'll create follow-up issues for the other topics discussed above.

Thanks!

**Comment by fthevenet** [comment]
> I wondered about implementing the ObservableList interface directly in the MRU

I thought about it but the MRU is based around a stack rather than a randomly accessible list (as it helps enforce the "most recent" semantics) so it cannot be done  without breaking things.

**Pull request merged**
