### PR TITLE
Fix Linux upgrade

### PR DESCRIPTION
**Pull request by Arkanosis**
This patchset should fix Linux upgrade. I believe the actual issue is not so much the working directory (though this had to be fixed anyway) but the fact that the upgrade script had lost its execution rights in e44711ee330cee55b9b0a23fab98739da9a4c042, breaking all upgrades on Linux (ie. not only when started from KDE Plasma).

### CODE REVIEW

**Review by fthevenet — COMMENTED** [review]
Am I correct in thinking this change, although necessary, is not enough to get the update fully working on macOS?

**Comment by Arkanosis** [comment]
> Am I correct in thinking this change, although necessary, is not enough to get the update fully working on macOS?

You are correct: the grep issue remains :-/

**Review by fthevenet — APPROVED** [review]
Ok, we'll sort that other issue later.

**Review by fthevenet — APPROVED** [review]
Ok, this one is one entirely my fault (again...) :-/

**Review by fthevenet — APPROVED** [review]

**Review by fthevenet — APPROVED** [review]

**Pull request merged**
